# Generated by Django 3.2.25 on 2025-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresavibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre_nosotros',
            name='mision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sobre_nosotros',
            name='vision',
            field=models.TextField(),
        ),
    ]
